/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs/index'
import { Route as TabsAlertsRouteImport } from './routes/_tabs/alerts'
import { Route as TabsMarketplaceRouteImport } from './routes/_tabs/marketplace'
import { Route as TabsMeRouteImport } from './routes/_tabs/me'
import { Route as TabsMessagesRouteImport } from './routes/_tabs/messages'
import { Route as TabsGroupsIndexRouteImport } from './routes/_tabs/groups.index'
import { Route as TabsGroupsGroupIdRouteImport } from './routes/_tabs/groups.$groupId'
import { Route as TabsScheduleIndexRouteImport } from './routes/_tabs/schedule.index'
import { Route as TabsScheduleEventIdRouteImport } from './routes/_tabs/schedule.$eventId'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAlertsRoute = TabsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMarketplaceRoute = TabsMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMeRoute = TabsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMessagesRoute = TabsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TabsRoute,
} as any)
const TabsGroupsIndexRoute = TabsGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsGroupsGroupIdRoute = TabsGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsScheduleIndexRoute = TabsScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsScheduleEventIdRoute = TabsScheduleEventIdRouteImport.update({
  id: '/schedule/$eventId',
  path: '/schedule/$eventId',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/alerts': typeof TabsAlertsRoute
  '/marketplace': typeof TabsMarketplaceRoute
  '/me': typeof TabsMeRoute
  '/messages': typeof TabsMessagesRoute
  '/groups/$groupId': typeof TabsGroupsGroupIdRoute
  '/schedule/$eventId': typeof TabsScheduleEventIdRoute
  '/groups/': typeof TabsGroupsIndexRoute
  '/schedule/': typeof TabsScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof TabsAlertsRoute
  '/marketplace': typeof TabsMarketplaceRoute
  '/me': typeof TabsMeRoute
  '/messages': typeof TabsMessagesRoute
  '/': typeof TabsIndexRoute
  '/groups/$groupId': typeof TabsGroupsGroupIdRoute
  '/schedule/$eventId': typeof TabsScheduleEventIdRoute
  '/groups': typeof TabsGroupsIndexRoute
  '/schedule': typeof TabsScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/alerts': typeof TabsAlertsRoute
  '/_tabs/marketplace': typeof TabsMarketplaceRoute
  '/_tabs/me': typeof TabsMeRoute
  '/_tabs/messages': typeof TabsMessagesRoute
  '/_tabs/': typeof TabsIndexRoute
  '/_tabs/groups/$groupId': typeof TabsGroupsGroupIdRoute
  '/_tabs/schedule/$eventId': typeof TabsScheduleEventIdRoute
  '/_tabs/groups/': typeof TabsGroupsIndexRoute
  '/_tabs/schedule/': typeof TabsScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/marketplace'
    | '/me'
    | '/messages'
    | '/groups/$groupId'
    | '/schedule/$eventId'
    | '/groups/'
    | '/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/marketplace'
    | '/me'
    | '/messages'
    | '/'
    | '/groups/$groupId'
    | '/schedule/$eventId'
    | '/groups'
    | '/schedule'
  id:
    | '__root__'
    | '/_tabs'
    | '/_tabs/alerts'
    | '/_tabs/marketplace'
    | '/_tabs/me'
    | '/_tabs/messages'
    | '/_tabs/'
    | '/_tabs/groups/$groupId'
    | '/_tabs/schedule/$eventId'
    | '/_tabs/groups/'
    | '/_tabs/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/alerts': {
      id: '/_tabs/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof TabsAlertsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/marketplace': {
      id: '/_tabs/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof TabsMarketplaceRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/me': {
      id: '/_tabs/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof TabsMeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/messages': {
      id: '/_tabs/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof TabsMessagesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/groups/': {
      id: '/_tabs/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof TabsGroupsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/groups/$groupId': {
      id: '/_tabs/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof TabsGroupsGroupIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/schedule/': {
      id: '/_tabs/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof TabsScheduleIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/schedule/$eventId': {
      id: '/_tabs/schedule/$eventId'
      path: '/schedule/$eventId'
      fullPath: '/schedule/$eventId'
      preLoaderRoute: typeof TabsScheduleEventIdRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAlertsRoute: typeof TabsAlertsRoute
  TabsMarketplaceRoute: typeof TabsMarketplaceRoute
  TabsMeRoute: typeof TabsMeRoute
  TabsMessagesRoute: typeof TabsMessagesRoute
  TabsIndexRoute: typeof TabsIndexRoute
  TabsGroupsGroupIdRoute: typeof TabsGroupsGroupIdRoute
  TabsScheduleEventIdRoute: typeof TabsScheduleEventIdRoute
  TabsGroupsIndexRoute: typeof TabsGroupsIndexRoute
  TabsScheduleIndexRoute: typeof TabsScheduleIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAlertsRoute: TabsAlertsRoute,
  TabsMarketplaceRoute: TabsMarketplaceRoute,
  TabsMeRoute: TabsMeRoute,
  TabsMessagesRoute: TabsMessagesRoute,
  TabsIndexRoute: TabsIndexRoute,
  TabsGroupsGroupIdRoute: TabsGroupsGroupIdRoute,
  TabsScheduleEventIdRoute: TabsScheduleEventIdRoute,
  TabsGroupsIndexRoute: TabsGroupsIndexRoute,
  TabsScheduleIndexRoute: TabsScheduleIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
